### PR TITLE
black code formatting

### PR DESCRIPTION
**Pull request by aniketmaurya**
Hi @lucidrains, this PR is for Black code formatting.

## Why Black?
Quoting from the project itself - 

> Black makes code review faster by producing the smallest diffs possible. Blackened code looks the same regardless of the project you’re reading. Formatting becomes transparent after a while and you can focus on the content instead.

a `pre-commit` hook can also be installed to automatically format the code on each commit.

Let me know if you want to merge it then I will be happy to add a `pre-commit` hook PR as well :)

Thanks 😊

### CODE REVIEW

**Comment by lucidrains** [comment]
@aniketmaurya hey sure! yea, i was a full stack developer for over a decade, i know what linting is

why did black produce https://github.com/lucidrains/PaLM-pytorch/pull/3/files#diff-a5ba5faa1b15b08f73db45e9342fcadc130f44195e1a0b082fa3d9b3e025885cR197 ?

**Comment by aniketmaurya** [comment]
I think that might be due to single line length and code + comment might be taking more characters than the specified (default 88 rn).

**Comment by lucidrains** [comment]
lgtm! :pray:

**Comment by lucidrains** [comment]
some day in the future, these attention nets will dynamically capture each person's style, and we can view another's code in our own style, irregardless of how it is produced

**Pull request merged**
